# Generated by Django 2.2.5 on 2020-05-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20200509_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='guests',
            field=models.IntegerField(help_text='몇 명이 머물 예정입니까?'),
        ),
    ]
